name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Init, Plan, Apply
    runs-on: agent-azure-dev

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4  # Change this to your preferred version

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      # - name: Terraform Plan
      #   run: terraform plan -out=tfplan

      # - name: Terraform Apply (Auto Apply)
      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      #   run: terraform apply -auto-approve tfplan
